#!/bin/bash
# lint check taken from http://www.sitepoint.com/git-hooks-fun-profit/
 
git diff --cached --name-status --diff-filter=ACMR | while read STATUS FILE; do
if [[ "$FILE" =~ ^.+(php|inc)$ ]]; then
    php -l "$FILE" 1> /dev/null
    if [ $? -ne 0 ]; then
        echo "Aborting commit due to files with syntax errors" >&2
        exit 1
    fi
fi
done
